---
# tasks file for docker-install
- name: Install ca-certificates curl
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - mc
    state: present
    update_cache: yes

- name: Create directory for keyring
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download docker repo key
  ansible.builtin.get_url:
    url: http://10.210.2.103/repository/packages/docker/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '644'

- name: Make docker.list for apt
  ansible.builtin.template:
    src: ./templates/docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: Install docker packages
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Make docker.list for apt
  ansible.builtin.template:
    src: ./templates/daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: docker-restart
