- hosts: runtime
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: roles/ubuntu-sysconf-optimize

    - ansible.builtin.import_role:
        name: roles/ubuntu-env-optimize

    - ansible.builtin.import_role:
        name: roles/repositories

    - ansible.builtin.import_role:
        name: roles/siem-apply-os
