---
# tasks file for ubuntu-env-optimize
- name: Set timezone to {{ local_timezone }}
  community.general.timezone:
    name: "{{ local_timezone }}"

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
